# Map of tags for cpg-common images
bcftools = '1.16'
bedtools = '2.30.0'
cellregmap = '0.0.3'
dragmap = '1.3.0'
expansionhunter = '5.0.0'
fastqc = '0.11.9'
gatk = '4.2.6.1'
hap-py = '0.3.15'
multipy = '0.16'
multiqc = '1.14'
peer = '1.3'
picard = '2.27.4'
reviewer = '0.2.7'
samblaster = '0.1.26'
samtools = '1.16.1'
somalier = '0.2.15'
trtools = '4.0.2'
vep = '105.0'
verifybamid = '2.0.1'
stripy = '2.2'
gangstr = '2.5.0'
hipstr = 'v0.6.2'
