# Map of tags for cpg-common images
bcftools = '1.16'
bedtools = '2.30.0'
bwa = '0.7.17'
cellregmap = '0.0.3'
dragmap = '1.3.0-tokenizer-next-fix'
expansionhunter = '5.0.0'
expansionhunter_bw2 = 'b85cba004fba4e0223e632fae576bc7fad0da804'
fastp = '0.23.4'
fastqe = '0.3.1'
fastqc = '0.11.9'
fraser = '1.12.1'
gatk = '4.2.6.1'
hap-py = '0.3.15'
haplocheckcli = '64293b3481d52025a01a293f6cc891546c30660e'
mitoreport = '1.1.0'
multipy = '0.16'
multiqc = '1.14'
outrider = '1.18.1'
peer = '1.3'
picard = '2.27.4'
reviewer = '0.2.7'
reviewer_bw2 = '0.2.7-bw2-fork-0.2'
saige-qtl = '8d840248fc025d5f58577ef03a6c23634ee941e5'
sambamba = '1.0.1'
samblaster = '0.1.26'
samtools = '1.18'
scanpy = '1.9.3'
scanpy_sctransform = '1.0'
somalier = '0.2.15'
star = '2.7.10b'
strvctvre = 'v.1.10'
subread = '2.0.6'
trtools = '5.0.2'
vep_105 = '105.0'
vep_110 = 'release_110.1'
verifybamid = '2.0.1'
stripy = '4e393f921d15bfba8e3c2234b20c483c205ac295'
gangstr = '2.5.0'
hipstr = 'v0.6.2'
bgt = 'v1.0'
basespace = '1.5.3'
